# Generated by Django 4.1 on 2024-05-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={"db_table": "auth_group", "managed": False,},
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[("id", models.BigAutoField(primary_key=True, serialize=False)),],
            options={"db_table": "auth_group_permissions", "managed": False,},
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={"db_table": "auth_permission", "managed": False,},
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={"db_table": "auth_user", "managed": False,},
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[("id", models.BigAutoField(primary_key=True, serialize=False)),],
            options={"db_table": "auth_user_groups", "managed": False,},
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[("id", models.BigAutoField(primary_key=True, serialize=False)),],
            options={"db_table": "auth_user_user_permissions", "managed": False,},
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={"db_table": "django_admin_log", "managed": False,},
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={"db_table": "django_content_type", "managed": False,},
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={"db_table": "django_migrations", "managed": False,},
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={"db_table": "django_session", "managed": False,},
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=255, null=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("register_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "admin", "managed": True,},
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=255, null=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("group_name", models.CharField(blank=True, max_length=255, null=True)),
                ("cross", models.CharField(blank=True, max_length=255, null=True)),
                ("register_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "student", "managed": True,},
        ),
        migrations.CreateModel(
            name="StudentGraduateAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("brief", models.CharField(blank=True, max_length=255, null=True)),
                ("student_id", models.IntegerField(blank=True, null=True)),
                (
                    "student_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("teacher_id", models.IntegerField(blank=True, null=True)),
                (
                    "teacher_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "third_score",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "third_remark",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "graduate_rank",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={"db_table": "student_graduate_answer", "managed": True,},
        ),
        migrations.CreateModel(
            name="StudentGraduateArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("brief", models.CharField(blank=True, max_length=255, null=True)),
                ("student_id", models.IntegerField(blank=True, null=True)),
                (
                    "student_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("teacher_id", models.IntegerField(blank=True, null=True)),
                (
                    "teacher_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "guide_score",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "guide_remark",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("view_score", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "view_remark",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "article_docx",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("total_docx", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"db_table": "student_graduate_article", "managed": True,},
        ),
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("student_id", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "student_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("count", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "student_group", "managed": True,},
        ),
        migrations.CreateModel(
            name="StudentMiddleCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("brief", models.CharField(blank=True, max_length=255, null=True)),
                ("student_id", models.IntegerField(blank=True, null=True)),
                (
                    "student_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("teacher_id", models.IntegerField(blank=True, null=True)),
                (
                    "teacher_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "second_score",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "second_remark",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={"db_table": "student_middle_check", "managed": True,},
        ),
        migrations.CreateModel(
            name="StudentSelectTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("brief", models.CharField(blank=True, max_length=255, null=True)),
                ("student_id", models.IntegerField(blank=True, null=True)),
                (
                    "student_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("teacher_id", models.IntegerField(blank=True, null=True)),
                (
                    "teacher_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("task_docx", models.CharField(blank=True, max_length=255, null=True)),
                ("guide_docx", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"db_table": "student_select_title", "managed": True,},
        ),
        migrations.CreateModel(
            name="StudentTitleMsg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("brief", models.CharField(blank=True, max_length=255, null=True)),
                ("student_id", models.IntegerField(blank=True, null=True)),
                (
                    "student_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("teacher_id", models.IntegerField(blank=True, null=True)),
                (
                    "teacher_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "first_score",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "first_remark",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "english_score",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "english_remark",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("title_docx", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "english_docx",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("apply_docx", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"db_table": "student_title_msg", "managed": True,},
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=255, null=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("group_type", models.CharField(blank=True, max_length=255, null=True)),
                ("group_name", models.CharField(blank=True, max_length=255, null=True)),
                ("register_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "teacher", "managed": True,},
        ),
        migrations.CreateModel(
            name="TeacherGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("teacher_id", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "teacher_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("count", models.IntegerField(blank=True, null=True)),
                (
                    "teacher_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={"db_table": "teacher_group", "managed": True,},
        ),
    ]
